### ISSUE TITLE
Renaming yaml fields and supporting multiple topics

### ISSUE THREAD

**Issue by RValner** [temoto-framework/temoto_visualization_manager#2]
Just as a reference, here's an example of how the yaml file currently is structured:

```yaml
Plugins:
- type: "image"
  class_name: "rviz/Image"
  rviz_name: "Temoto Image"
  data_type: "sensor_msgs/Image"

- type: "laser_scan"
  class_name: "rviz/LaserScan"
  rviz_name: "Temoto Laser Scan"
  data_type: "sensor_msgs/LaserScan" 
```

So the first problem is that the field names in the yaml description are quite confusing, so i propose:

* we should get rid of the `type`
* `class_name` -> `plugin_name`
* `rviz_name` -> `name_seen_by_user`
* `data_type` -> `visualized_data`

Which brings us to the second issue, lack of support for multiple topics, thus I think the `visualized_data` should be a vector of key value pairs (example):

```yaml
visualized_data:
  - laserscan: "sensor_msgs/LaserScan"
```
or

```yaml
visualized_data:
  - panospheric_image_front: "sensor_msgs/Image"
  - panospheric_image_back: "sensor_msgs/Image"
```

This would require some changes both in the `visualization_manager.cpp` and `visualization_manager_interface.h` so that user can specify the topics.
